# Generated by Django 5.1.5 on 2025-02-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='clear',
            field=models.BooleanField(default=True),
        ),
    ]
